from enum import Enum

class StrategyType(Enum):
    WAIT = "WAIT"
    ATM_STRADDLE = "ATM_STRADDLE"
    ATM_STRANGLE = "ATM_STRANGLE"
    SHORT_STRANGLE = "SHORT_STRANGLE"
    IRON_CONDOR = "IRON_CONDOR"
    DEFENSIVE_IRON_CONDOR = "DEFENSIVE_IRON_CONDOR"
    BULL_PUT_SPREAD = "BULL_PUT_SPREAD"
    CALENDAR_SPREAD = "CALENDAR_SPREAD"
    RATIO_SPREAD = "RATIO_SPREAD"

class TradeStatus(Enum):
    PENDING = "PENDING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    EXTERNAL = "EXTERNAL"
    REJECTED = "REJECTED"

class OrderStatus(Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    PARTIAL = "PARTIAL"

class ExitReason(Enum):
    PROFIT_TARGET = "PROFIT_TARGET"
    STOP_LOSS = "STOP_LOSS"
    EXPIRY = "EXPIRY"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    RISK_BREACH = "RISK_BREACH"
    MANUAL = "MANUAL"

class CapitalBucket(Enum):
    WEEKLY = "weekly_expiries"
    MONTHLY = "monthly_expiries"
    INTRADAY = "intraday_adjustments"

class ExpiryType(Enum):
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    INTRADAY = "INTRADAY"

class MarketRegime(Enum):
    PANIC = "PANIC"
    FEAR_BACKWARDATION = "FEAR_BACKWARDATION"
    LOW_VOL_COMPRESSION = "LOW_VOL_COMPRESSION"
    CALM_COMPRESSION = "CALM_COMPRESSION"
    DEFENSIVE_EVENT = "DEFENSIVE_EVENT"
    BULL_EXPANSION = "BULL_EXPANSION"  # ADDED - Was missing
    BEAR_CONTRACTION = "BEAR_CONTRACTION"  # ADDED - For completeness
    TRANSITION = "TRANSITION"
