from enum import Enum 

class TradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PENDING = "PENDING"
    EXTERNAL = "EXTERNAL"
    CANCELLED = "CANCELLED"
    
class ExitReason(str, Enum):
    PROFIT_TARGET = "PROFIT_TARGET"
    STOP_LOSS = "STOP_LOSS"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    EOD_FLATTEN = "EOD_FLATTEN"
    EXPIRY_FLATTEN = "EXPIRY_FLATTEN"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    MANUAL = "MANUAL"
    VEGA_LIMIT = "VEGA_LIMIT"
    DELTA_LIMIT = "DELTA_LIMIT"
    REGIME_CHANGE = "REGIME_CHANGE"
    HEALTH_CHECK = "HEALTH_CHECK"
    
class OrderStatus(str, Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    FILLED = "FILLED"
    PARTIAL_FILLED = "PARTIAL_FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"

class OrderType(str, Enum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"
    SL = "SL"
    SL_M = "SL-M"

class MarketRegime(str, Enum):
    PANIC = "PANIC"
    FEAR_BACKWARDATION = "FEAR_BACKWARDATION"
    DEFENSIVE_EVENT = "DEFENSIVE_EVENT"
    BULL_EXPANSION = "BULL_EXPANSION"
    CALM_COMPRESSION = "CALM_COMPRESSION"
    LOW_VOL_COMPRESSION = "LOW_VOL_COMPRESSION"
    TRANSITION = "TRANSITION"
    UNSTABLE_HIGH_VOL = "UNSTABLE_HIGH_VOL"
